#+TITLE: Docker setup

* Developing image

emane needs a hosts file for names node-1, etc.

Add in /etc/hosts

#+begin_example
#emane

10.99.0.1 node-1
10.99.0.2 node-2
10.99.0.3 node-3
10.99.0.4 node-4
10.99.0.5 node-5
10.99.0.6 node-6
10.99.0.7 node-7
10.99.0.8 node-8
10.99.0.9 node-9
10.99.0.10 node-10
10.99.0.100 node-server
10.100.0.1 radio-1
10.100.0.2 radio-2
10.100.0.3 radio-3
10.100.0.4 radio-4
10.100.0.5 radio-5
10.100.0.6 radio-6
10.100.0.7 radio-7
10.100.0.8 radio-8
10.100.0.9 radio-9
10.100.0.10 radio-10
#+end_example

Also, you probably want to setup rsa authorization for logging into
the nodes. Just

#+begin_example
ssh-keyben -b 4096
ssh-copy-id localhsot
#+end_example

These will generate in .ssh/ the id_rsa, id_rsa.pub, authorized_keys.

Now when the demo starts, you can ssh into a node via:

#+begin_example
ssh node-1
#+end_example

* building image

#+begin_example
docker build -t myimage .
#+end_example

To test

#+begin_example
docker run -it --rm myimage
#+end_example

* Running the container
To really use the VM:

FIXME print the ID

#+begin_example
docker run -itd --privileged myimage
#+end_example

If using d, it will be detached, but the IP address is not printed out
either. So to see the IP address:

#+begin_example
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container_id>
#+end_example

I probably want to create a named container for long-term usage:

#+begin_example
docker run -itd --name my-name myimage
#+end_example

Or I can see the logs by:

#+begin_example
docker logs <container_id>
#+end_example

* Inside the VM

The lxd daemon should be running. But I'll need to manually init the
lxd (only for the first time) with:

#+begin_example
sudo lxd init --auto
#+end_example
